### ISSUE TITLE
[cdn][waiting...] Adding es6-tween to CDNjs libraries list/folder

### ISSUE THREAD

**Issue by dalisoft** [tweenjs/es6-tween#15]
Someone can help with this issue?

**Comment by dalisoft** [comment]
@PeterDaveHello @PeterBot helped me with that, so soon our library would be available on @cdnjs

**Comment by dalisoft** [comment]
@jsdelivr adds library maximum 3day, if much of PR (50+ in day). I not understanding why @cdnjs takes much of time? it's interesting? maybe @cdnjs needs help?

**Comment by dalisoft** [comment]
@cdnjs one of bad cdn i ever see. They delay merging PR insteadof helping. I just love @jsdelivr

**Comment by PeterDaveHello** [comment]
Sorry to make you feel that but we have tons of issues to handle so it's reasonable to have delay and we already tried the best to handle that, @cdnjs as you can see has almost 3k libraries to maintain and have more than 700 issues waiting on the list, that's why it'll be slower, hope this make your understood, it's a fully free and open source project, feel free to point out the problem or fix it.
